//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioAdmin.ServiceReferenceEmprunts {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCountEmprunt", Namespace="http://schemas.datacontract.org/2004/07/wcflibrary")]
    [System.SerializableAttribute()]
    public partial class clsCountEmprunt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbreEmpruntField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbreEmprunt {
            get {
                return this.NbreEmpruntField;
            }
            set {
                if ((this.NbreEmpruntField.Equals(value) != true)) {
                    this.NbreEmpruntField = value;
                    this.RaisePropertyChanged("NbreEmprunt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceEmprunts.IServiceEmprunts")]
    public interface IServiceEmprunts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/InsertEmprunt", ReplyAction="http://tempuri.org/IServiceEmprunts/InsertEmpruntResponse")]
        void InsertEmprunt(string titre, string nom, System.Nullable<System.DateTime> dtRetour, decimal prixEmprunt, string biblio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/InsertEmprunt", ReplyAction="http://tempuri.org/IServiceEmprunts/InsertEmpruntResponse")]
        System.Threading.Tasks.Task InsertEmpruntAsync(string titre, string nom, System.Nullable<System.DateTime> dtRetour, decimal prixEmprunt, string biblio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/UpdateEmprunt", ReplyAction="http://tempuri.org/IServiceEmprunts/UpdateEmpruntResponse")]
        void UpdateEmprunt(int id, System.DateTime dtRetour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/UpdateEmprunt", ReplyAction="http://tempuri.org/IServiceEmprunts/UpdateEmpruntResponse")]
        System.Threading.Tasks.Task UpdateEmpruntAsync(int id, System.DateTime dtRetour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/LoadAllEmprunt", ReplyAction="http://tempuri.org/IServiceEmprunts/LoadAllEmpruntResponse")]
        System.Data.DataSet LoadAllEmprunt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/LoadAllEmprunt", ReplyAction="http://tempuri.org/IServiceEmprunts/LoadAllEmpruntResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LoadAllEmpruntAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexePrincipal", ReplyAction="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexePrincipalResponse")]
        BiblioAdmin.ServiceReferenceEmprunts.clsCountEmprunt[] NbreEmpruntAnnexePrincipal(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexePrincipal", ReplyAction="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexePrincipalResponse")]
        System.Threading.Tasks.Task<BiblioAdmin.ServiceReferenceEmprunts.clsCountEmprunt[]> NbreEmpruntAnnexePrincipalAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexe", ReplyAction="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexeResponse")]
        BiblioAdmin.ServiceReferenceEmprunts.clsCountEmprunt[] NbreEmpruntAnnexe(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexe", ReplyAction="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexeResponse")]
        System.Threading.Tasks.Task<BiblioAdmin.ServiceReferenceEmprunts.clsCountEmprunt[]> NbreEmpruntAnnexeAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexePrincipalAdo", ReplyAction="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexePrincipalAdoResponse")]
        int NbreEmpruntAnnexePrincipalAdo(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexePrincipalAdo", ReplyAction="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexePrincipalAdoResponse")]
        System.Threading.Tasks.Task<int> NbreEmpruntAnnexePrincipalAdoAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexeAdo", ReplyAction="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexeAdoResponse")]
        int NbreEmpruntAnnexeAdo(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexeAdo", ReplyAction="http://tempuri.org/IServiceEmprunts/NbreEmpruntAnnexeAdoResponse")]
        System.Threading.Tasks.Task<int> NbreEmpruntAnnexeAdoAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/InsertEmpruntEF", ReplyAction="http://tempuri.org/IServiceEmprunts/InsertEmpruntEFResponse")]
        void InsertEmpruntEF(string titre, string nom, System.Nullable<System.DateTime> dtRetour, decimal prixEmprunt, string biblio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmprunts/InsertEmpruntEF", ReplyAction="http://tempuri.org/IServiceEmprunts/InsertEmpruntEFResponse")]
        System.Threading.Tasks.Task InsertEmpruntEFAsync(string titre, string nom, System.Nullable<System.DateTime> dtRetour, decimal prixEmprunt, string biblio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEmpruntsChannel : BiblioAdmin.ServiceReferenceEmprunts.IServiceEmprunts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEmpruntsClient : System.ServiceModel.ClientBase<BiblioAdmin.ServiceReferenceEmprunts.IServiceEmprunts>, BiblioAdmin.ServiceReferenceEmprunts.IServiceEmprunts {
        
        public ServiceEmpruntsClient() {
        }
        
        public ServiceEmpruntsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEmpruntsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpruntsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpruntsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertEmprunt(string titre, string nom, System.Nullable<System.DateTime> dtRetour, decimal prixEmprunt, string biblio) {
            base.Channel.InsertEmprunt(titre, nom, dtRetour, prixEmprunt, biblio);
        }
        
        public System.Threading.Tasks.Task InsertEmpruntAsync(string titre, string nom, System.Nullable<System.DateTime> dtRetour, decimal prixEmprunt, string biblio) {
            return base.Channel.InsertEmpruntAsync(titre, nom, dtRetour, prixEmprunt, biblio);
        }
        
        public void UpdateEmprunt(int id, System.DateTime dtRetour) {
            base.Channel.UpdateEmprunt(id, dtRetour);
        }
        
        public System.Threading.Tasks.Task UpdateEmpruntAsync(int id, System.DateTime dtRetour) {
            return base.Channel.UpdateEmpruntAsync(id, dtRetour);
        }
        
        public System.Data.DataSet LoadAllEmprunt() {
            return base.Channel.LoadAllEmprunt();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LoadAllEmpruntAsync() {
            return base.Channel.LoadAllEmpruntAsync();
        }
        
        public BiblioAdmin.ServiceReferenceEmprunts.clsCountEmprunt[] NbreEmpruntAnnexePrincipal(string user) {
            return base.Channel.NbreEmpruntAnnexePrincipal(user);
        }
        
        public System.Threading.Tasks.Task<BiblioAdmin.ServiceReferenceEmprunts.clsCountEmprunt[]> NbreEmpruntAnnexePrincipalAsync(string user) {
            return base.Channel.NbreEmpruntAnnexePrincipalAsync(user);
        }
        
        public BiblioAdmin.ServiceReferenceEmprunts.clsCountEmprunt[] NbreEmpruntAnnexe(string user) {
            return base.Channel.NbreEmpruntAnnexe(user);
        }
        
        public System.Threading.Tasks.Task<BiblioAdmin.ServiceReferenceEmprunts.clsCountEmprunt[]> NbreEmpruntAnnexeAsync(string user) {
            return base.Channel.NbreEmpruntAnnexeAsync(user);
        }
        
        public int NbreEmpruntAnnexePrincipalAdo(string user) {
            return base.Channel.NbreEmpruntAnnexePrincipalAdo(user);
        }
        
        public System.Threading.Tasks.Task<int> NbreEmpruntAnnexePrincipalAdoAsync(string user) {
            return base.Channel.NbreEmpruntAnnexePrincipalAdoAsync(user);
        }
        
        public int NbreEmpruntAnnexeAdo(string user) {
            return base.Channel.NbreEmpruntAnnexeAdo(user);
        }
        
        public System.Threading.Tasks.Task<int> NbreEmpruntAnnexeAdoAsync(string user) {
            return base.Channel.NbreEmpruntAnnexeAdoAsync(user);
        }
        
        public void InsertEmpruntEF(string titre, string nom, System.Nullable<System.DateTime> dtRetour, decimal prixEmprunt, string biblio) {
            base.Channel.InsertEmpruntEF(titre, nom, dtRetour, prixEmprunt, biblio);
        }
        
        public System.Threading.Tasks.Task InsertEmpruntEFAsync(string titre, string nom, System.Nullable<System.DateTime> dtRetour, decimal prixEmprunt, string biblio) {
            return base.Channel.InsertEmpruntEFAsync(titre, nom, dtRetour, prixEmprunt, biblio);
        }
    }
}
